name: build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      OS: linux
    steps:
      - name: Environment
        run: set
      - uses: actions/checkout@v2
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '22.3.0'
          java: 'java17'
      - name: Install native-image
        run: gu install native-image
      - name: Run test scenario
        run: |
          cd quarkus-maven-sample-project
          ./test.sh
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"

