name: build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      OS: linux
    steps:
      - name: Environment
        run: set
      - uses: actions/checkout@v2
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '22.3.0'
          java: 'java17'
      - name: Install native-image
        run: gu install native-image
      - name: Build Quarkus Maven extension
        run: |
          cd quarkus-custom-user-data-maven-extension
          ./mvnw -B install
          cd ..
      - name: Run test scenario
        run: |
          cd quarkus-maven-sample-project
          ./test.sh
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"

  build-win64:
    runs-on: windows-2019
    env:
      OS: windows
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: 21.3.0
          java: java11
      - name: Install native-image
        run: |
          %JAVA_HOME%/bin/gu.cmd install native-image
        shell: cmd
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
      - name: Build Quarkus Maven extension
        run: |
            cd quarkus-custom-user-data-maven-extension
            ./mvnw -B install
            cd ..
#      - name: Run build 1 - Expect no config dump
#        run: |
#            cd quarkus-maven-sample-project
#            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
#            ./mvnw -B clean package -DskipTests
#            cd ..
#        env:
#            GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
#        shell: cmd
#      - name: Run build 2 - Expect cache miss
#        run: |
#            cd quarkus-maven-sample-project
#            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
#            ./mvnw -B clean package -DskipTests
#            cd ..
#        env:
#            GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
#        shell: cmd
#      - name: Run build 3 - Expect cache hit
#        run: |
#            cd quarkus-maven-sample-project
#            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
#            ./mvnw -B clean package -DskipTests
#            cd ..
#        env:
#            GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
#        shell: cmd
#      - name: Run build 4 - Expect property changed
#        run: |
#          cd quarkus-maven-sample-project
#          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
#          ./mvnw -B clean package -DskipTests -Dquarkus.live-reload.retry-interval=15s
#          cd ..
#        env:
#          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
#        shell: cmd
#      - name: Run build 5 - Expect cache hit
#        run: |
#            cd quarkus-maven-sample-project
#            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
#            ./mvnw -B clean package -DskipTests -Dquarkus.live-reload.retry-interval=15s
#            cd ..
#        env:
#            GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
#        shell: cmd
      - name: Run build 6 - Expect cache miss
        run: |
            cd quarkus-maven-sample-project
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            #if not exist %VCVARS% set VCVARS="C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            #call %VCVARS%
            ./mvnw -B clean package -DskipTests -Dnative -Dquarkus.live-reload.retry-interval=15s
            cd ..
        env:
            GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        shell: cmd
      - name: Run build 7 - Expect cache hit
        run: |
            cd quarkus-maven-sample-project
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            #if not exist %VCVARS% set VCVARS="C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            #call %VCVARS%
            ./mvnw -B clean package -DskipTests -Dnative -Dquarkus.live-reload.retry-interval=15s
            cd ..
        env:
            GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        shell: cmd
      - name: Run build 8 - Expect no config dump
        run: |
            cd quarkus-maven-sample-project
            del .quarkus/*
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            #if not exist %VCVARS% set VCVARS="C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            #call %VCVARS%
            ./mvnw -B clean package -DskipTests -Dnative
            cd ..
        env:
            GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        shell: cmd
