name: build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      OS: linux
    steps:
      - name: Environment
        run: set
      - uses: actions/checkout@v2
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '22.3.0'
          java: 'java17'
      - name: Install native-image
        run: gu install native-image
      - name: Clone Quarkus
        uses: actions/checkout@v2
        with:
          repository: 'aloubyansky/quarkus'
          path: quarkus
          ref: dump-config-wip
      - name: Build Quarkus
        run: |
          cd quarkus
          ./mvnw install -Dquickly -T2C
          cd ..
      - name: Build Quarkus Maven extension
        run: |
          cd quarkus-custom-user-data-maven-extension
          ./mvnw -B install
          cd ..
      - name: Build 1
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        id: build1
        run: |
          cd quarkus-maven-sample-project
          ./mvnw -B clean package -DskipTests 2>&1 | tee -a /tmp/build.log
          echo "quarkusPropertiesNotFound=$(grep "Quarkus properties not found" /tmp/build.log | wc -l)" >> $GITHUB_OUTPUT
          echo "cachingNotPossible=$(grep "Caching not possible for Quarkus goal" /tmp/build.log | wc -l)" >> $GITHUB_OUTPUT
          cd ..
      - name: Validate Build 1 - cache miss
        run: exit 1
        if: steps.build1.outputs.quarkusPropertiesNotFound == '0' || steps.build1.outputs.cachingNotPossible == 0
        shell: bash
      - name: Build 2
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        id: build2
        run: |
          cd quarkus-maven-sample-project
          ./mvnw -B clean package -DskipTests 2>&1 | tee -a /tmp/build.log
          echo "cacheHit=$(grep "Configuring caching for Quarkus build" -A 1 /tmp/build.log | grep "Loaded from the build cache" | wc -l)" >> $GITHUB_OUTPUT
          cd ..
      - name: Validate Build 2 - cache hit
        run: exit 2
        if: steps.build2.outputs.cacheHit == '0'
        shell: bash
      - name: Build 3
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        id: build3
        run: |
          cd quarkus-maven-sample-project
          ./mvnw -B clean package -DskipTests -Dquarkus.live-reload.retry-interval=15s 2>&1 | tee -a /tmp/build.log
          echo "quarkusPropChanged=$(grep -E "Quarkus properties have changed.*quarkus.live-reload.retry-interval" /tmp/build.log | wc -l)" >> $GITHUB_OUTPUT
          cd ..
      - name: Validate Build 3 - cache miss
        run: exit 3
        if: steps.build3.outputs.quarkusPropChanged == '0'
        shell: bash
      - name: Build 4
        env:
            GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        id: build4
        run: |
            cd quarkus-maven-sample-project
            ./mvnw -B clean package -DskipTests -Dquarkus.live-reload.retry-interval=15s 2>&1 | tee -a /tmp/build.log
            echo "cacheHit=$(grep "Configuring caching for Quarkus build" -A 1 /tmp/build.log | grep "Loaded from the build cache" | wc -l)" >> $GITHUB_OUTPUT
            cd ..
      - name: Validate Build 4 - cache hit
        run: exit 4
        if: steps.build4.outputs.cacheHit == '0'
        shell: bash
